version: '2'
services:
  websocket1:
    build: .
    ports:
      - "5001:5001"
    links:
      - "redis:redis"
  websocket2:
    build: .
    ports:
      - "5002:5001"
    links:
      - "redis:redis"
  redis:
    image: redis
    ports:
      - "6379:6379"

